stages:
  - test
  - release

test:
  image: node
  stage: test
  script:
    - yarn
    - yarn run test
    - npx semantic-release --repository-url $CI_REPOSITORY_URL
  only:
    - master
  except:
    - /^chore(release).*$/

release:
  image: docker:latest
  stage: release
  script:
    - TAG="${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$TAG"
    - docker push "$CI_REGISTRY_IMAGE:$TAG"
  only:
    - tags

